server:
  # 端口号
  port: 10100
  servlet:
    # 编码设置
    encoding:
      charset: UTF-8
      force: true
spring:
  jmx:
    # 默认域
    default-domain: maven_springboot2
  jackson:
    # 不输出null值属性
    default-property-inclusion: non-null
    # 日期时间信息应答为时间戳
    serialization:
      write-dates-as-timestamps: true
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.huhuiyu.top:3306/db_test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: test
    password: User4-test
    hikari:
      connection-test-query: select 1
      max-lifetime: 60000
mybatis:
  type-aliases-package: top.huhuiyu.template.maven.springboot2.entity
  configuration:
    map-underscore-to-camel-case: true